const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "../..");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const files = ["index.html", "styles.css", "app.js", "src/domain.js", "src/storage.js", "src/admin.js", "src/ai.js", "src/lab-fixture.js", "src/finance-fixture.js", "src/recording-taxonomy.js"];
const source = files.map((file) => fs.readFileSync(path.join(root, file), "utf8")).join("\n");
const canonicalApi = fs.readFileSync(path.join(root, "src/canonical-api.js"), "utf8");

assert.doesNotMatch(source, /https?:\/\/[^\s"']*(?:workers\.dev|api\.line\.me|cloudflareworkers\.com)/i);
assert.doesNotMatch(source, /(?:LINE_CHANNEL_SECRET|CHANNEL_ACCESS_TOKEN|Authorization:\s*Bearer|wrangler\s+secret)/i);
assert.doesNotMatch(source, /\b(?:fetch|XMLHttpRequest|WebSocket)\s*\(/);
assert.doesNotMatch(source, /farm\.finance|farm\s*\[\s*["']finance["']\s*\]/);
assert.doesNotMatch(source, /https?:\/\//i);
assert.match(source, /SYNTHETIC_FINANCE_V1/);
assert.match(source, /classification:\s*"synthetic"/);
assert.match(source, /function escapeHtml\(value\)/);
assert.match(source, /parseQuickRecord/);
assert.match(source, /escapeHtml\(state\.quickRecordDraft\)/);
assert.match(source, /IndexedDB|indexedDB/);
assert.match(source, /clientOperationId/);
assert.match(source, /conflict/i);
assert.match(source, /AI_UNAVAILABLE/);
assert.match(canonicalApi, /\/api\/records/);
assert.match(canonicalApi, /normalizeCanonicalApiError/);
assert.match(canonicalApi, /payload\.error/);
assert.match(canonicalApi, /headers\.authorization/);
assert.match(canonicalApi, /credentials:\s*"omit"/);
assert.doesNotMatch(canonicalApi, /localStorage|indexedDB/i);
assert.match(canonicalApi, /LOCAL_HOSTNAMES/);
assert.doesNotMatch(canonicalApi, /(?:LINE_CHANNEL_SECRET|CHANNEL_ACCESS_TOKEN|wrangler\s+secret)/i);
const canonicalErrorMapper = app.slice(app.indexOf("function canonicalApiErrorMessage"), app.indexOf("function submitCanonicalBoundary"));
assert.match(canonicalErrorMapper, /invalid_credentials:\s*"登入未通過，請確認管理密碼後再試。"/);
assert.match(canonicalErrorMapper, /context === "login"/);
assert.doesNotMatch(canonicalErrorMapper, /error\?\.message/);
console.log("SECURITY_PASS", JSON.stringify({ files: files.length + 1, labRuntimeNetwork: 0, canonicalApiBoundary: true, productionSecrets: 0, xssEscaping: true }));
