(function attachJinjiFinanceFixture(root, factory) {
  const api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  if (root) root.JinjiFinanceFixture = api;
})(typeof window === "object" ? window : (typeof globalThis === "object" ? globalThis : null), () => {
  "use strict";

  /* Synthetic-only public Lab fixture. It is intentionally independent from the operational fixture. */
  return {
    metadata: {
      classification: "synthetic",
      datasetId: "SYNTHETIC_FINANCE_V1",
      schemaVersion: 1,
    },
    organization: {
      id: "syn-org-001",
      name: "模擬投資組合",
    },
    farms: [
      { id: "syn-farm-a", name: "模擬場 A", farmTotalEquityFraction: 0.35, playerGroupEquityFraction: 0.12, active: true },
      { id: "syn-farm-b", name: "模擬場 B", farmTotalEquityFraction: 0.40, playerGroupEquityFraction: 0.15, active: true },
      { id: "syn-farm-c", name: "模擬場 C", farmTotalEquityFraction: 0.30, playerGroupEquityFraction: 0.10, active: true },
      { id: "syn-farm-d", name: "模擬場 D", farmTotalEquityFraction: 0.45, playerGroupEquityFraction: 0.20, active: true },
      { id: "syn-farm-e", name: "模擬場 E", farmTotalEquityFraction: 0.25, playerGroupEquityFraction: 0.09, active: true },
      { id: "syn-farm-f", name: "模擬場 F", farmTotalEquityFraction: 0.38, playerGroupEquityFraction: 0.14, active: true },
      { id: "syn-farm-g", name: "模擬場 G", farmTotalEquityFraction: 0.50, playerGroupEquityFraction: 0.18, active: true },
      { id: "syn-farm-h", name: "模擬場 H", farmTotalEquityFraction: 0.32, playerGroupEquityFraction: 0.12, active: true },
    ],
    investors: [
      { id: "syn-investor-a", name: "模擬投資人 A", active: true },
      { id: "syn-investor-b", name: "模擬投資人 B", active: true },
      { id: "syn-investor-c", name: "模擬投資人 C", active: true },
    ],
    farmInvestorEquity: [
      { id: "syn-equity-a-a", farmId: "syn-farm-a", investorId: "syn-investor-a", equityFraction: 0.05, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-a-b", farmId: "syn-farm-a", investorId: "syn-investor-b", equityFraction: 0.04, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-a-c", farmId: "syn-farm-a", investorId: "syn-investor-c", equityFraction: 0.03, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-b-a", farmId: "syn-farm-b", investorId: "syn-investor-a", equityFraction: 0.05, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-b-b", farmId: "syn-farm-b", investorId: "syn-investor-b", equityFraction: 0.05, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-b-c", farmId: "syn-farm-b", investorId: "syn-investor-c", equityFraction: 0.05, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-c-a", farmId: "syn-farm-c", investorId: "syn-investor-a", equityFraction: 0.04, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-c-b", farmId: "syn-farm-c", investorId: "syn-investor-b", equityFraction: 0.03, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-c-c", farmId: "syn-farm-c", investorId: "syn-investor-c", equityFraction: 0.03, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-d-a", farmId: "syn-farm-d", investorId: "syn-investor-a", equityFraction: 0.08, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-d-b", farmId: "syn-farm-d", investorId: "syn-investor-b", equityFraction: 0.07, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-d-c", farmId: "syn-farm-d", investorId: "syn-investor-c", equityFraction: 0.05, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-e-a", farmId: "syn-farm-e", investorId: "syn-investor-a", equityFraction: 0.03, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-e-b", farmId: "syn-farm-e", investorId: "syn-investor-b", equityFraction: 0.03, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-e-c", farmId: "syn-farm-e", investorId: "syn-investor-c", equityFraction: 0.03, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-f-a", farmId: "syn-farm-f", investorId: "syn-investor-a", equityFraction: 0.06, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-f-b", farmId: "syn-farm-f", investorId: "syn-investor-b", equityFraction: 0.04, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-f-c", farmId: "syn-farm-f", investorId: "syn-investor-c", equityFraction: 0.04, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-g-a", farmId: "syn-farm-g", investorId: "syn-investor-a", equityFraction: 0.06, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-g-b", farmId: "syn-farm-g", investorId: "syn-investor-b", equityFraction: 0.06, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-g-c", farmId: "syn-farm-g", investorId: "syn-investor-c", equityFraction: 0.06, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-h-a", farmId: "syn-farm-h", investorId: "syn-investor-a", equityFraction: 0.04, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-h-b", farmId: "syn-farm-h", investorId: "syn-investor-b", equityFraction: 0.05, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
      { id: "syn-equity-h-c", farmId: "syn-farm-h", investorId: "syn-investor-c", equityFraction: 0.03, source: "synthetic_fixture", effectiveDate: "2035-01-01" },
    ],
    distributions: [
      { id: "syn-distribution-01", organizationId: "syn-org-001", farmId: "syn-farm-a", distributionDate: "2035-01-10", sourceDateRoc: "124/01/10", grossProfitLoss: 120000, allocatedProfitLoss: 14400, expense: 0, netIncome: 14400, note: "Synthetic settlement 01", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-01" },
      { id: "syn-distribution-02", organizationId: "syn-org-001", farmId: "syn-farm-b", distributionDate: "2035-02-14", sourceDateRoc: "124/02/14", grossProfitLoss: 86000, allocatedProfitLoss: 12900, expense: 500, netIncome: 12400, note: "Synthetic settlement 02", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-02" },
      { id: "syn-distribution-03", organizationId: "syn-org-001", farmId: "syn-farm-c", distributionDate: "2035-03-06", sourceDateRoc: "124/03/06", grossProfitLoss: 76000, allocatedProfitLoss: 7600, expense: 0, netIncome: 7600, note: "Synthetic settlement 03", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-03" },
      { id: "syn-distribution-04", organizationId: "syn-org-001", farmId: "syn-farm-a", distributionDate: "2035-04-18", sourceDateRoc: "124/04/18", grossProfitLoss: -45000, allocatedProfitLoss: -5400, expense: 1200, netIncome: -6600, note: "Synthetic settlement 04", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-04" },
      { id: "syn-distribution-05", organizationId: "syn-org-001", farmId: "syn-farm-d", distributionDate: "2035-05-11", sourceDateRoc: "124/05/11", grossProfitLoss: 99000, allocatedProfitLoss: 19800, expense: 1600, netIncome: 18200, note: "Synthetic settlement 05", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-05" },
      { id: "syn-distribution-06", organizationId: "syn-org-001", farmId: "syn-farm-e", distributionDate: "2035-06-03", sourceDateRoc: "124/06/03", grossProfitLoss: 135000, allocatedProfitLoss: 12150, expense: 300, netIncome: 11850, note: "Synthetic settlement 06", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-06" },
      { id: "syn-distribution-07", organizationId: "syn-org-001", farmId: "syn-farm-f", distributionDate: "2035-07-27", sourceDateRoc: "124/07/27", grossProfitLoss: 64000, allocatedProfitLoss: 8960, expense: 0, netIncome: 8960, note: "Synthetic settlement 07", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-07" },
      { id: "syn-distribution-08", organizationId: "syn-org-001", farmId: "syn-farm-b", distributionDate: "2035-08-22", sourceDateRoc: "124/08/22", grossProfitLoss: 142000, allocatedProfitLoss: 21300, expense: 0, netIncome: 21300, note: "Synthetic settlement 08", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-08" },
      { id: "syn-distribution-09", organizationId: "syn-org-001", farmId: "syn-farm-d", distributionDate: "2035-09-19", sourceDateRoc: "124/09/19", grossProfitLoss: -28000, allocatedProfitLoss: -5600, expense: 800, netIncome: -6400, note: "Synthetic settlement 09", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-09" },
      { id: "syn-distribution-10", organizationId: "syn-org-001", farmId: "syn-farm-g", distributionDate: "2035-10-08", sourceDateRoc: "124/10/08", grossProfitLoss: 111000, allocatedProfitLoss: 19980, expense: 900, netIncome: 19080, note: "Synthetic settlement 10", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-10" },
      { id: "syn-distribution-11", organizationId: "syn-org-001", farmId: "syn-farm-h", distributionDate: "2035-11-16", sourceDateRoc: "124/11/16", grossProfitLoss: 53000, allocatedProfitLoss: 6360, expense: 0, netIncome: 6360, note: "Synthetic settlement 11", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-11" },
      { id: "syn-distribution-12", organizationId: "syn-org-001", farmId: "syn-farm-c", distributionDate: "2036-01-25", sourceDateRoc: "125/01/25", grossProfitLoss: 88000, allocatedProfitLoss: 8800, expense: 700, netIncome: 8100, note: "Synthetic settlement 12", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-12" },
    ],
    allocations: [
      { id: "syn-allocation-01-a", distributionId: "syn-distribution-01", investorId: "syn-investor-a", amount: 6000 },
      { id: "syn-allocation-01-b", distributionId: "syn-distribution-01", investorId: "syn-investor-b", amount: 4800 },
      { id: "syn-allocation-01-c", distributionId: "syn-distribution-01", investorId: "syn-investor-c", amount: 3600 },
      { id: "syn-allocation-02-a", distributionId: "syn-distribution-02", investorId: "syn-investor-a", amount: 4133.333333333333 },
      { id: "syn-allocation-02-b", distributionId: "syn-distribution-02", investorId: "syn-investor-b", amount: 4133.333333333333 },
      { id: "syn-allocation-02-c", distributionId: "syn-distribution-02", investorId: "syn-investor-c", amount: 4133.333333333334 },
      { id: "syn-allocation-03-a", distributionId: "syn-distribution-03", investorId: "syn-investor-a", amount: 3040 },
      { id: "syn-allocation-03-b", distributionId: "syn-distribution-03", investorId: "syn-investor-b", amount: 2280 },
      { id: "syn-allocation-03-c", distributionId: "syn-distribution-03", investorId: "syn-investor-c", amount: 2280 },
      { id: "syn-allocation-04-a", distributionId: "syn-distribution-04", investorId: "syn-investor-a", amount: -2750 },
      { id: "syn-allocation-04-b", distributionId: "syn-distribution-04", investorId: "syn-investor-b", amount: -2200 },
      { id: "syn-allocation-04-c", distributionId: "syn-distribution-04", investorId: "syn-investor-c", amount: -1650 },
      { id: "syn-allocation-05-a", distributionId: "syn-distribution-05", investorId: "syn-investor-a", amount: 7280 },
      { id: "syn-allocation-05-b", distributionId: "syn-distribution-05", investorId: "syn-investor-b", amount: 6370 },
      { id: "syn-allocation-05-c", distributionId: "syn-distribution-05", investorId: "syn-investor-c", amount: 4550 },
      { id: "syn-allocation-06-a", distributionId: "syn-distribution-06", investorId: "syn-investor-a", amount: 3950 },
      { id: "syn-allocation-06-b", distributionId: "syn-distribution-06", investorId: "syn-investor-b", amount: 3950 },
      { id: "syn-allocation-06-c", distributionId: "syn-distribution-06", investorId: "syn-investor-c", amount: 3950 },
      { id: "syn-allocation-07-a", distributionId: "syn-distribution-07", investorId: "syn-investor-a", amount: 3840 },
      { id: "syn-allocation-07-b", distributionId: "syn-distribution-07", investorId: "syn-investor-b", amount: 2560 },
      { id: "syn-allocation-07-c", distributionId: "syn-distribution-07", investorId: "syn-investor-c", amount: 2560 },
      { id: "syn-allocation-08-a", distributionId: "syn-distribution-08", investorId: "syn-investor-a", amount: 7100 },
      { id: "syn-allocation-08-b", distributionId: "syn-distribution-08", investorId: "syn-investor-b", amount: 7100 },
      { id: "syn-allocation-08-c", distributionId: "syn-distribution-08", investorId: "syn-investor-c", amount: 7100 },
      { id: "syn-allocation-09-a", distributionId: "syn-distribution-09", investorId: "syn-investor-a", amount: -2560 },
      { id: "syn-allocation-09-b", distributionId: "syn-distribution-09", investorId: "syn-investor-b", amount: -2240 },
      { id: "syn-allocation-09-c", distributionId: "syn-distribution-09", investorId: "syn-investor-c", amount: -1600 },
      { id: "syn-allocation-10-a", distributionId: "syn-distribution-10", investorId: "syn-investor-a", amount: 6360 },
      { id: "syn-allocation-10-b", distributionId: "syn-distribution-10", investorId: "syn-investor-b", amount: 6360 },
      { id: "syn-allocation-10-c", distributionId: "syn-distribution-10", investorId: "syn-investor-c", amount: 6360 },
      { id: "syn-allocation-11-a", distributionId: "syn-distribution-11", investorId: "syn-investor-a", amount: 2120 },
      { id: "syn-allocation-11-b", distributionId: "syn-distribution-11", investorId: "syn-investor-b", amount: 2650 },
      { id: "syn-allocation-11-c", distributionId: "syn-distribution-11", investorId: "syn-investor-c", amount: 1590 },
      { id: "syn-allocation-12-a", distributionId: "syn-distribution-12", investorId: "syn-investor-a", amount: 3240 },
      { id: "syn-allocation-12-b", distributionId: "syn-distribution-12", investorId: "syn-investor-b", amount: 2430 },
      { id: "syn-allocation-12-c", distributionId: "syn-distribution-12", investorId: "syn-investor-c", amount: 2430 },
    ],
    sourceReferences: [
      { id: "syn-source-01", distributionId: "syn-distribution-01", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-01", sourceDateRoc: "124/01/10" },
      { id: "syn-source-02", distributionId: "syn-distribution-02", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-02", sourceDateRoc: "124/02/14" },
      { id: "syn-source-03", distributionId: "syn-distribution-03", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-03", sourceDateRoc: "124/03/06" },
      { id: "syn-source-04", distributionId: "syn-distribution-04", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-04", sourceDateRoc: "124/04/18" },
      { id: "syn-source-05", distributionId: "syn-distribution-05", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-05", sourceDateRoc: "124/05/11" },
      { id: "syn-source-06", distributionId: "syn-distribution-06", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-06", sourceDateRoc: "124/06/03" },
      { id: "syn-source-07", distributionId: "syn-distribution-07", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-07", sourceDateRoc: "124/07/27" },
      { id: "syn-source-08", distributionId: "syn-distribution-08", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-08", sourceDateRoc: "124/08/22" },
      { id: "syn-source-09", distributionId: "syn-distribution-09", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-09", sourceDateRoc: "124/09/19" },
      { id: "syn-source-10", distributionId: "syn-distribution-10", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-10", sourceDateRoc: "124/10/08" },
      { id: "syn-source-11", distributionId: "syn-distribution-11", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-11", sourceDateRoc: "124/11/16" },
      { id: "syn-source-12", distributionId: "syn-distribution-12", sourceDataset: "SYNTHETIC_FINANCE_V1", sourceRowKey: "fixture://finance/TX-12", sourceDateRoc: "125/01/25" },
    ],
  };
});
